### PR TITLE
add public getters for comment and options

### PR DESCRIPTION
**Pull request by Trolldemorted**
implements #13.

If you merge this it would be very kind if you'd push a new version to crates.io.

cc @fsck @bitwave @gehaxelt

### CODE REVIEW

**Comment by Trolldemorted** [comment]
:+1:

We could also modify the struct and make the fields public - whatever you prefer.

**Comment by sdemos** [comment]
actually, now that you mention it, I think I would prefer to just have all the fields of the struct public. While you are at it, can you also make the fields in the `Data` enum public as well? I don't see any reason why we shouldn't provide access to all the information we are parsing out of the keys.

**Comment by Trolldemorted** [comment]
Sure!

Shall I remove set_comment?

**Comment by Trolldemorted** [comment]
I have amended my commit!

Enums are always public, aren't they?

**Comment by sdemos** [comment]
oh, yup, looks like they are. I thought the enum variant fields would behave like struct fields but it seems like I'm wrong. 

I think we can probably leave `set_comment` around. It does remove a little bit of boilerplate if you are setting the comment to a hardcoded string.

**Comment by Trolldemorted** [comment]
AppVeyor & Travis tests have passed, as we expected.

:shipit:

**Comment by sdemos** [comment]
v0.2.2 is released with this change included. it's been uploaded on crates.io. thanks!

**Pull request merged**
